### ISSUE TITLE
Create a handler that compares the performed exposure analysis of multiple predefined adaptation options

### ISSUE THREAD

**Issue by sahand-asgarpour** [Deltares/ra2ce#286]
@daniel:
- [ ] create a column (flooded_EV1-EV2) in the hazard overlay graph and network for the pairwise comparison of EV1 EV2 (refering to the flooding events 1 and 2 and ...). If a link is flooded in both (EV_i_ma > threshold) or only EV2 then flooded_EV1-EV2 = 1 otherwise 0

**Comment by LiekeMeijer** [comment]
Comparing results of the 'base-scenario' with results of the 'adaptation scenario'. Should be coded generically so that any adaptation option can be compared and there are options to handle multiple scenario comparison. 

- [ ] Load results of the base scenario with hazard
- [ ] Define how to generate results for the adaptation scenario(s) #create a seperate issue for this
- [ ] Load results of the adaptation scenario(s) with hazard
- [ ] Compare the results of both scenarios
- [ ] Give the comparison back as result
